### ISSUE TITLE
Dont you have upgrade this library components to latest react-native version?

### ISSUE THREAD

**Issue by susylPearl** [ayoubdev/react-native-android-kit#4]
always shows an error in proptypes when i run this library to my latest react-native version i.e 0.26

**Comment by ayoubdev** [comment]
Hello @susylPearl ,

Please, give me a screenshot of your error or at least a text copy paste.

**Comment by iheart2code** [comment]
Just create a new project with latest react native and try to use this module. React Native has moved a few imports, causing some errors. In particular, the imports for Component & PropTypes should come from 'react', not 'react-native'.

Hope this helps.

**Comment by ayoubdev** [comment]
Solved: now needs react-native >= 0.29.0
